### ISSUE TITLE
Example on how to use JWT with RSA

### ISSUE THREAD

**Issue by mirzaciri** [mulesoft/data-weave-jwt-library#24]
Is there an example of how to use the jwt::RSA with a private key (passphrase)?

I see that in the example for RSA, it specifies a **key** as an input, but an example on how to use it from a keystore or directly from a file read would be appreciated.

**Comment by teofr** [comment]
Hey @mirzaciri, thanks for taking an interest!

You could use the [`readUrl`](https://docs.mulesoft.com/dataweave/2.4/dw-core-functions-readurl) function to read from a file, for example:
```dataweave
%dw 2.0
import * from jwt::RSA

output application/json
var key = readUrl("classpath://mySecret.txt", "text/plain")

---
{
	token: JWT(
		{
			iss: "some@email.com",
			aud: 'https://oauth2.googleapis.com/token',
			scope: 'https://www.googleapis.com/auth/drive.readonly',
			iat: now() as Number { unit: 'seconds' },
			exp: (now() + |PT3600S|) as Number { unit: 'seconds' }
		},
		key
	),
	expiration: now() + |PT3550S|
}
```

Regarding a keystore, I guess it would depend on each particular case. However, this is out of scope for this library, so we won't be adding this example case to the repo.

Let me know if you need help with anything else.

**Comment by mirzaciri** [comment]
> Hey @mirzaciri, thanks for taking an interest!
> 
> You could use the [`readUrl`](https://docs.mulesoft.com/dataweave/2.4/dw-core-functions-readurl) function to read from a file, for example:
> 
> ```data-weave
> %dw 2.0
> import * from jwt::RSA
> 
> output application/json
> var key = readUrl("classpath://mySecret.txt", "text/plain")
> 
> ---
> {
> 	token: JWT(
> 		{
> 			iss: "some@email.com",
> 			aud: 'https://oauth2.googleapis.com/token',
> 			scope: 'https://www.googleapis.com/auth/drive.readonly',
> 			iat: now() as Number { unit: 'seconds' },
> 			exp: (now() + |PT3600S|) as Number { unit: 'seconds' }
> 		},
> 		key
> 	),
> 	expiration: now() + |PT3550S|
> }
> ```
> 
> Regarding a keystore, I guess it would depend on each particular case. However, this is out of scope for this library, so we won't be adding this example case to the repo.
> 
> Let me know if you need help with anything else.

thanks for the reply @teofr 
From my understanding, and after looking at the readurl, it does not support opening it up with a password/passphrase. 

And if that is not supported, and as well as Keystore, then the JWT with RSA (private key) is not supported, don't you agree?
Storing the content of the certificate in plain text is not secure.

I know one solution is to have it as a encrypted value in a config file using secure properties, but that is also not a good solution.

**Comment by teofr** [comment]
Hey, I agree that storing it in plain text is not a good idea, I misunderstood you. There are other options available, like using environment variables, or passing the key as an input to the mapping, that can be easily used in DW today.

This library is intended only for the JWT generation, storing and retrieving keys is not part of this functionality (and it could be useful in other places as well), so it should probably be considered for another library.

**Comment by mirzaciri** [comment]
> Hey, I agree that storing it in plain text is not a good idea, I misunderstood you. There are other options available, like using environment variables, or passing the key as an input to the mapping, that can be easily used in DW today.
> 
> This library is intended only for the JWT generation, storing and retrieving keys is not part of this functionality (and it could be useful in other places as well), so it should probably be considered for another library.

I guess that makes sense, thanks for the explanation @teofr

ill try and find a way to view the content of the certification in a different way then!
